version: "3.8"
services:
  app:
    container_name: hmtjk_app
    build: ./app
    volumes:
      - ./app:/var/www/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www
      - ./nginx/:/etc/nginx/conf.d/
      - ./ssl/:/etc/ssl/
    networks:
      - app-network
  db:
    image: mysql:8.0
    restart: "always"
    env_file: ./.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - '13306:3306'
    volumes:
      - ./volumes/db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
    networks:
      - app-network
  phpmyadmin:
      image: bitnami/phpmyadmin:5.0.2-debian-10-r72
      ports:
        - 8080:80
        - 8443:443
      environment:
          DATABASE_HOST: db
      restart: always
networks:
  app-network:
    driver: bridge
